/************************************************************
**
**  This file is automagically generated.
**  DO NOT EDIT IT
**  It is generated by gen_board_config.py
**  
**  It was generated on Fri Sep  9 21:49:27 2011
**
**  Information contained herein is proprietary to and constitutes valuable
**  confidential trade secrets of G2 Microsystems Pty. Ltd., or its licensors, and
**  is subject to restrictions on use and disclosure.
**
**  Copyright (c) 2008 G2 Microsystems Pty. Ltd. All rights reserved.
**
**  The copyright notices above do not evince any actual or
**  intended publication of this material.
************************************************************/


// Board configuration application dispatch header.
#include <board_config.mdk_rev3.h>

